### ISSUE TITLE
Azure?

### ISSUE THREAD

**Issue by planetzeos** [soajs/soajs.installer#10]
Istruzioni di Azure?

https://soajsorg.atlassian.net/wiki/spaces/IN/pages/64293432/Microsoft+Azure

**Comment by antoinehage** [comment]
documentation updated, please check: 
- docker azure: https://soajsorg.atlassian.net/wiki/spaces/IN/pages/881917976/Azure+Docker
- kubernetes azure: https://soajsorg.atlassian.net/wiki/spaces/IN/pages/881983503/Azure+Kubernetes
